### ISSUE TITLE
[Cannonup] Bug when loading a new round

### ISSUE THREAD

**Issue by Seniru** [Lautenschlager-id/Transformice#1]
This issue is related with cannonup module and  doesn't occurs all the time. I think this is a problem with a map

## Steps to reproduce
 - Play as usual
 - Win a round
 - This bug won't appear all the time as I mentioned earlier. So you have to pass multiple rounds to get this issue

## Expected
 - Stopping of spawning of cannons
 - A new round starts as normal

## Actual
 - Prints somebody won
 - Starts the countdown for the next map
 - Cannons keep spawning
 - New round won't start and keeps counting for the next map continuously

*I hope this could be fixed quickly as all of the mice have to get away from the room to fix this by themselves*

**Comment by Lautenschlager-id** [comment]
https://github.com/a801-luadev/cannonup/issues/1
